FROM python:3.12.1-slim

LABEL maintainer="solairen@solairen.tech"
LABEL python=3.12.1
LABEL sphinx=7.2.6

ARG workdir=/sphinx

COPY requirements-furo.txt /requirements.txt

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install git -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && mkdir ${workdir} \
    && pip install --upgrade pip \
    && pip install -r /requirements.txt --no-cache-dir \
    && rm /requirements.txt

WORKDIR ${workdir}
ENTRYPOINT [ "sphinx-build", "-aE" ]