name: Docker registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Set docker image version."
        required: true

env:
  DOCKER_USER: ${{ secrets.docker_username }}
  DOCKER_TOKEN: ${{ secrets.docker_token }}
  VERSION: ${{ github.event.inputs.version }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Push docker image to docker hub
    runs-on: ubuntu-24.04

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          moleszek/sphinx:latest
          moleszek/sphinx:${{ env.VERSION }}
          ghcr.io/solairen/docker_sphinx/sphinx:latest
          ghcr.io/solairen/docker_sphinx/sphinx:${{ env.VERSION }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile-furo
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          moleszek/sphinx-furo:latest
          moleszek/sphinx-furo:${{ env.VERSION }}
          ghcr.io/solairen/docker_sphinx/sphinx-furo:latest
          ghcr.io/solairen/docker_sphinx/sphinx-furo:${{ env.VERSION }}