name: Docker registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Set docker image version."
        required: true

env:
  DOCKER_USER: ${{ secrets.docker_username }}
  DOCKER_TOKEN: ${{ secrets.docker_token }}
  VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        push: true
        tags: moleszek/sphinx:${{ env.VERSION }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        push: true
        tags: moleszek/sphinx:latest
    - name: Build and push with Furo theme
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile-furo
        push: true
        tags: moleszek/sphinx-furo:${{ env.VERSION }}
    - name: Build and push with Furo theme
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile-furo
        push: true
        tags: moleszek/sphinx-furo:latest
