name: Test docker image
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Test-build Docker image
    runs-on: ubuntu-24.04

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          moleszek/sphinx:latest
          ghcr.io/solairen/docker_sphinx/sphinx:latest

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile-furo
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          moleszek/sphinx-furo:latest
          ghcr.io/solairen/docker_sphinx/sphinx-furo:latest