name: Test docker image
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

env:
  GH_TOKEN: ${{ secrets.token }}
  DISCORD: ${{ secrets.discord_webhook }}

jobs:
  test:
    name: Test-build Docker image
    runs-on: ubuntu-latest
    container: docker:stable
    steps:
    - name: Set up buidlix
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Test build
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        push: false
        tags: sphinx:test
  notify_on_success:
    name: Send notification on success
    needs:
      - test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          description: "Successfully test docker image!"
  notify_on_failure:
    name: Send notification on failure
    needs:
      - test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          status: failure
          description: "Failed to test docker image!"
